{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: microconfig
  annotations: {{ toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  {{ if .Values.ingress.tls.enabled }}
  tls:
    - secretName: {{ .Values.ingress.tls.secret }}
      hosts:
        - {{ .Values.ingress.host }}
  {{end}}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - pathType: Prefix
            path: "/api"
            backend:
              serviceName: {{ .Chart.Name }}
              servicePort: http
  {{end}}