apiVersion: v1
kind: Secret
metadata:
  name: microconfig-secret
type: Opaque
data:
  remote: {{.Values.config.remote | b64enc }}
  username: {{.Values.config.username | toString | b64enc }}
  password: {{.Values.config.password | toString | b64enc}}
