replicas: 1

image:
  repo: microconfig/server
  tag: 0.5.0

serviceAccount: default

service:
  type: ClusterIP

pod:
  annotations: {}

ingress:
  enabled: false
  host: server.microconfig.io
  class: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  tls:
    enabled: false
    secret: microconfig-tls

# default values. override with your own
config:
  remote: https://github.com/microconfig/microconfig-quickstart.git
  username: open
  password: source
